config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  resources :books, only: [:index, :show] do
    resources :chapters, only: [:index, :show]
  end

  resource :authors, only: [:show] do
    resources :books, only: [:index, :new, :create, :show, :edit, :update], controller: 'authors/books'
  end

  resource :welcome, only: [:show]

  root to: 'welcome#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save :downcase_email

  has_many :books

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :chapters
  belongs_to :author

  validates :title, presence: true

  # used for creating css class names
  def classify
    remove_symbols(title.split.map(&:capitalize).join('').concat(id.to_s))
  end

  private

  def remove_symbols(str)
    str.gsub(/[^0-9A-Za-z]/, '')
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book

  validates :index, presence: true

  def blurb
    return '...' if contents.nil?

    "#{contents[0, blurb_length]}..."
  end

  private

  def blurb_length
    max_blurb_length = 100
    contents.length > max_blurb_length ? max_blurb_length : contents.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/books_controller.rb
module Authors
  class BooksController < AuthenticatedController
    def index
      @books = Book.where(author: current_author)
      render locals: { books: @books }
    end

    def show
      @book = Book.find(params[:id])
      render locals: { book: @book }
    end

    def edit
      @book = Book.find(params[:id])
      render :edit, locals: { book: @book }
    end

    def new
      @book = Book.new
      render locals: { book: @book }
    end

    def create
      @book = Book.new book_params
      if @book.save
        redirect_to @book
      else
        flash.notice = "Book not created: #{@book.errors.full_messages}"
        redirect_to new_authors_book_path, locals: { book: @book }
      end
    end

    def update
      @book = Book.find(params[:id])
      if @book.update book_params
        redirect_to @book
      else
        flash.notice = "Book not updated: #{@book.errors.full_messages}"
        redirect_to edit_authors_book_path, locals: { book: @book }
      end
    end

    private

    def book_params
      params[:book][:author_id] = current_author.id
      params.require(:book).permit(:title, :author_id, :image_url)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < AuthenticatedController
  def show
    @author = current_author
    render :show, locals: { author: @author }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    render :index, locals: { books: @books }
  end

  def show
    @book = Book.find(params[:id])
    render :show, locals: { book: @book }
  end

  def edit
    @book = Book.find(params[:id])
    render :edit, locals: { book: @book }
  end

  private

  def book_params
    params.require(:book).permit(:title, :author_id, :image_url)
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    book.chapters.new(chapter_params).save
    redirect_to edit_book_path(book), locals: { chapter: @chapter, book: book }
  end

  def create
    @chapter = Chapter.new(chapter_params)
  end

  def show
    @chapter = Chapter.find(params[:id])
    @book = Book.find(params[:book_id])
    render :show, locals: { chapter: @chapter, book: @book }
  end

  private

  attr_accessor :book

  def chapter_params
    {
      index: next_index,
      contents: nil,
      book_id: params[:book_id]
    }
  end

  def next_index
    return 1 if book.chapters.empty?

    book.chapters.last.index + 1
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/application/_content.html.erb
<div class="Content">
  <%= render "flash" %>
  <%= yield %>
</div>

app/views/application/_flash.html.erb
<div>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</div>

app/views/application/_footer.html.erb
<div class="Footer">
  <p>@https://github.com/KarlWinkler/Authorly-rails</p>
</div>

app/views/application/_navbar.html.erb
<section class="Navbar">
  <%= link_to 'home', '/', class: 'Navbar-link' %>
  <div class="Navbar-login-info">
  <% if author_signed_in? %>
    Logged in as <strong> <%= current_author.name %></strong>.
    <%= link_to 'Profile', authors_path, class: 'navbar-link' %> |
    <%= link_to "Logout", destroy_author_session_path, data: {turbo_method: :delete}, class: 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_author_registration_path, class: 'navbar-link'  %> |
    <%= link_to "Login", new_author_session_path, class: 'navbar-link'  %>
  <% end %>
  </div>
</section>

app/views/authors/books/edit.html.erb
<%= render partial: 'templates/book', locals: { book: book, classes_for_book: "Book--medium" } %>

<%= form_for :book, url: authors_book_path(book), method: :patch do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.submit %>
<% end %>

<p>Title: <%= book.title %></p>
<p>Author: <%= book.author %></p>

<h3>Chapters</h3>
<% book.chapters.each do |chapter| %>
    <a href=<%= book_chapter_path(book_id: book.id, id: chapter.id)  %>>
    <%= render partial: 'templates/chapter', locals: { chapter: chapter } %>
    </a>
<% end %>

<%# <%= link_to 'New Chapter', new_book_chapter_path(book_id: book.id) %>

app/views/authors/books/index.html.erb
<%= render partial: 'templates/title', locals: { title: 'My Book' } %>

<%= render partial: 'templates/books_list', locals: { books: books }%>

app/views/authors/books/new.html.erb
<h1>New Book</h1>

<%= form_for book, url: { action: :create } do |f| %>
  <div>
    <%= f.label :image_url%><br>
    <%= f.text_field :image_url %>
  </div>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<%end%>

app/views/authors/show.html.erb
<h1>Hello <%= @author.name %></h1>
<ul>
  <li><%= link_to 'my books', authors_books_path %></li>
  <li><%= link_to 'new book', new_authors_book_path %></li>

  <li><%= link_to 'edit profile', edit_author_registration_path %></li>
  <li><%= link_to 'my books', authors_books_path %></li>

  <li><%= link_to 'my books', authors_books_path %></li>
</ul>

app/views/books/_select_book.html.erb
<div class="Card--select-card">
  <img class="<%= "BookImage #{classes_for_book}" %>" src=<%= book.image_url%> alt="cover image"> 
  <p class="BookTitle"><%= book.title %></p>
</div>

app/views/books/edit.html.erb
<%= render partial: 'templates/book', locals: { book: book, classes_for_book: "Book--medium" } %>

<p>Title: <%= book.title %></p>
<p>Author: <%= book.author %></p>

<h3>Chapters</h3>
<% book.chapters.each do |chapter| %>
    <a href=<%= book_chapter_path(book_id: book.id, id: chapter.id)  %>>
    <%= render partial: 'templates/chapter', locals: { chapter: chapter } %>
    </a>
<% end %>

<%= link_to 'New Chapter', new_book_chapter_path(book_id: book.id) %>

app/views/books/index.html.erb
<%= render partial: 'templates/title', locals: { title: 'Select A Book' } %>

<%= render partial: 'templates/books_list', locals: { books: books }%>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with model: @book do |f| %>
  <div>
    <%= f.label :image_url%><br>
    <%= f.text_field :image_url %>
  </div>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<%end%>

app/views/books/show.html.erb
<%= render partial: 'templates/book', locals: { book:book, classes_for_book: "BookImage-large" } %>

<%= link_to "edit", edit_authors_book_path if current_author == book.author%>
<p>Title: <%= book.title %></p>
<p>Author: <%= book.author.name %></p>

<h3>Chapters</h3>
<% book.chapters.each do |chapter| %>
    <a href=<%= "#{book.id}/chapters/#{chapter.id}" %>>
    <%= render partial: 'templates/chapter', locals: { chapter: chapter } %>
    </a><br><br>
<% end %>

app/views/chapters/new.html.erb
<%# this should not exist unless its only purpose is to create a chapter (maybe if I want to to make chapter creation more robust later ) %>

<%= render partial: 'templates/book', locals: { book:book, scale: "25%" } %>

<p>Title: <%= book.title %></p>
<p>Author: <%= book.author %></p>

<br>
<br>
<h3>Chapters</h3>
<% book.chapters.each do |chapter| %>
    <a href=/chapter/<%= chapter.id %>>
    <%= render partial: 'templates/chapter', locals: { chapter: chapter } %>
    </a><br><br>
<% end %>

<%= form_with model: [book, chapter] do |f| %>
  <div>
    <%= f.submit %>
  </div>
<%end%>

app/views/chapters/show.html.erb
<p>Title: <%= chapter.index %></p>
<br>
<p>Author: <%= chapter.contents %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorlyRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "navbar" %>
    <%= render "content" %>
    <%= render "footer" %>
  </body>
</html>

app/views/templates/_book.html.erb
<img src=<%= book.image_url%> alt="cover image" width=<%= scale %> height=<%= scale %>> <br><%= book.title %>

app/views/templates/_books_list.html.erb
<div class="CardContainer">
<% books.each do |book| %>
    <%= render partial: 'templates/selection_card', locals: { book: book } %>
<% end %>
</div>

app/views/templates/_chapter.html.erb
<div>
  <p> <%= chapter.index %></p>
  <p> <%= chapter.blurb %></p>
</div>

app/views/templates/_selection_card.erb
<section class="SelectionCardWrapper">
  <article class="SelectionCard SelectionCard--<%= book.classify %>">
    <a href=/books/<%= book.id %>>
    <div class="SelectionCard-info-hover">
    </div>
    <div class="SelectionCard-img"></div>
       <div class="SelectionCard-img--hover"></div>
    <div class="SelectionCard-info">
      <span class="SelectionCard-category"><%= book.category %></span>
      <h3 class="SelectionCard-title"><%= book.title %></h3>
      <span class="SelectionCard-by">by <p href="#" class="SelectionCard-author" title="author"><%= book.author.name %></p></span>
    </div>   
    </a>
  </article>
</section>

<style>
.SelectionCard--<%= book.classify %> .SelectionCard-img, .SelectionCard--<%= book.classify %> .SelectionCard-img--hover {
  background-image: url('<%= book.image_url %>');
}
</style>

app/views/templates/_title.html.erb
<div class="Title">
  <h1 class="Title--name"><%= title %></h1>
</div>

app/views/welcome/show.html.erb
<div class="WelcomeWrapper">
  <a href="/books/">View all books</a>
</div>